#!/bin/bash
#SBATCH --job-name=wgs-msweep-metaphlan-wgs2
#SBATCH --output=/wrk/users/temaklin/wgs-msweep/logs/wgs-msweep-metaphlan-wgs2.out
#SBATCH -e /wrk/users/temaklin/wgs-msweep/logs/wgs-msweep-metaphlan-wgs2.err
#SBATCH -t 01:59:59
#SBATCH -M ukko2
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH -c 8
#SBATCH --mem-per-cpu=512
#SBATCH --mail-type=NONE
#SBATCH --mail-user=tommi.maklin@helsinki.fi
#SBATCH --hint=compute_bound
#SBATCH --hint=nomultithread
#SBATCH --array=1-2

export LC_ALL="C"
export LANG="C"

basedir=$WRKDIR/wgs-msweep

accession=$(sed -n "${SLURM_ARRAY_TASK_ID}p" $basedir/missing_accessions.txt)
fwd=$basedir/data/wgs-reads/$accession""_1.fastq
rev=$basedir/data/wgs-reads/$accession""_2.fastq

bowtie2db=$WRKDIR/metaphlan-db
outdir=$basedir/out/metaphlan

source ~/.bashrc
conda activate metaphlan

metaphlan --bowtie2db $bowtie2db $fwd,$rev --bowtie2out $outdir/bowtie2out/wgs/$accession.bowtie2.bz2 --nproc 8 --input_type fastq -o $outdir/profiles/wgs/$accession.txt --unknown_estimation --add_viruses
