#!/bin/bash
#SBATCH --job-name=wgs-msweep-k-qva-strain-bins
#SBATCH --output=/wrk/users/temaklin/wgs-msweep/logs/wgs-msweep-k-qva-strain-bins.out
#SBATCH -e /wrk/users/temaklin/wgs-msweep/logs/wgs-msweep-k-qva-strain-bins.err
#SBATCH -t 07:59:59
#SBATCH -M ukko2,ukko
#SBATCH --ntasks=1
#SBATCH --cpus-per-task 1
#SBATCH --mem-per-cpu=8192
#SBATCH --hint=nomultithread
#SBATCH --array=1-13

export LC_ALL="C"
export LANG="C"

## module load GCC/10.2.0 CMake/3.18.4-GCCcore-10.2.0
module load CMake GCC

nprocs=1
nthreads=1

species="K_qva"

basedir=$WRKDIR/wgs-msweep
info=$(sed -n "${SLURM_ARRAY_TASK_ID} p" $basedir/out/$species""_bins.txt)
accession=$(echo $info | grep -o "ERR[0-9]*")

# fwd=$basedir/data/wgs-reads/$accession""_1.fastq.gz
# rev=$basedir/data/wgs-reads/$accession""_2.fastq.gz

bin=$basedir/out/mGEMS/$info
# mkdir $basedir/out/mGEMS/$accession/$species
# $USERAPPL/mGEMS/build/bin/mGEMS extract --bins $bin -r $fwd,$rev -o $basedir/out/mGEMS/$accession/$species

fwd=$basedir/out/mGEMS/$accession/$species/$species""_1.fastq.gz
rev=$basedir/out/mGEMS/$accession/$species/$species""_2.fastq.gz

fwdaln=$basedir/out/themisto/$accession/$species""_1.aln
revaln=$basedir/out/themisto/$accession/$species""_2.aln

# indexdir=$WRKDIR/cocov2-reference-sequences/$species/$species""_index
# tmpdir=$basedir/out/themisto/$accession/$species""_tmp
# mkdir $tmpdir

# grouping=$WRKDIR/cocov2-reference-sequences/$species/$species""_grouping.indis

# $USERAPPL/themisto/build/bin/pseudoalign --query-file $fwd --outfile $fwdaln --index-dir $indexdir --temp-dir $tmpdir --rc --n-threads $nthreads --gzip-output --sort-output
# $USERAPPL/themisto/build/bin/pseudoalign --query-file $rev --outfile $revaln --index-dir $indexdir --temp-dir $tmpdir --rc --n-threads $nthreads --gzip-output --sort-output

# rm -rf $tmpdir

fwdaln=$fwdaln"".gz
revaln=$revaln"".gz

outdir=$basedir/out/mGEMS/$accession/$species

## $USERAPPL/mSWEEP-v1.6.0_beta/bin/mSWEEP-omp --themisto-1 $fwdaln --themisto-2 $revaln -i $grouping -t $nthreads -o $outdir/$species --print-probs | xz -c --threads $nthreads > $outdir/$species""_probs.csv.xz

probs=$basedir/out/mSWEEP/$accession/$species""_probs.csv.xz
abundances=$basedir/out/mSWEEP/$accession/$species""_abundances.txt
index=$basedir/reference/themisto-old-index-autocolors

$USERAPPL/mGEMS/build/bin/mGEMS bin --min-abundance 0.000001 --themisto-alns $fwdaln,$revaln -o $outdir --probs $probs -a $abundances --index $index
xz --extreme $outdir/*.bin
